name: Check for dead links

on:
  pull_request:
    branches: [main, 'v/*', archived-versions]
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
      - name: Check dead links
        uses: hazelcast/hazelcast-docs/.github/actions/validate@main
      - name: Check orphan pages
        run: npm run check-orphan-pages
