name: Check for dead links

on:
  pull_request:
    branches: [main, 'v/*', archived-versions]
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
      - name: Test install
#        run: npm i git+https://${{ github.token }}@github.com/hazelcast/hazelcast-docs-tools.git#v0.0.1-alpha
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN_DOCS_TOOLS }}@github.com/".insteadOf ssh://git@github.com/
          npm i git+https://${{ secrets.GH_TOKEN_DOCS_TOOLS }}@github.com/hazelcast/hazelcast-docs-tools.git
      - name: Check dead links
        uses: hazelcast/hazelcast-docs/.github/actions/validate@main
      - name: Check orphan pages
        shell: bash
        run: npm run check-orphan-pages
